---
title: "Summary Effect Sizes and Forest Plot"
output: html_notebook
---

# Summaries studies

## 2003_chen Summarizing table 

```{r}
chen_2003_summary <- chen_2003 |> 
  select(es, se, study, calculation_statistic, calculation_data, calculation_certainty)
```

## 2005_chen Summarizing table

```{r}
chen_2005_summary <- chen_2005 |> 
  select(es, se, study, calculation_statistic, calculation_data, calculation_certainty)
```

## 2006_cimmer Summarizing table

```{r}
cimmer_2006_summary <- cimmer_2006 |> 
  select(es, se, study, calculation_statistic, calculation_data, calculation_certainty)
```

## 2006_oDonnell Summarizing table

```{r}
oDonnell_2006_summary <- oDonnell_2006 |> 
  select(es, se, study, calculation_statistic, calculation_data, calculation_certainty)
```

## 2006_chen Summarizing table

```{r}
chen_2006_summary <- chen_2006 |> 
  select(es, se, study, calculation_statistic, calculation_data, calculation_certainty)
```

## 2013_cadenhead Summarizing table

```{r}
cadenhead_2013_summary <- cadenhead_2013 |> 
  select(es, se, study, calculation_statistic, calculation_data, calculation_certainty)
```

# Summary table all studies

Let's combine the data in a single data frame.

```{r,echo=TRUE}
studies <- chen_2003_summary |> 
  bind_rows(chen_2005_summary) |> 
  bind_rows(cimmer_2006_summary) |> 
  bind_rows(oDonnell_2006_summary) |> 
  bind_rows(chen_2006_summary) |>
  bind_rows(cadenhead_2013_summary) |>
  select(study, es, se, calculation_statistic, calculation_data, calculation_certainty)

studies
```


# Random-effect meta-analysis using `meta`

```{r,echo=TRUE}
random_meta <- metagen(TE = es, seTE = se, studlab = study, 
                    fixed = FALSE, 
                    random = TRUE, 
                    data = studies)

random_meta
```


```{r,echo=TRUE}
summary(random_meta)
```

### Forest plot Random effect

```{r,echo=TRUE}
forest(random_meta)
```


We can modify the plot

```{r,echo=TRUE}
forest(random_meta, layout= "JAMA", hetstat = FALSE, 
       xlim = c(-1, 2))
```


